### PR TITLE
chore(github): 🔧 ci cd for checking code style

### LINKED ISSUE #14: CI/CD for checking prettier/lint
### Describe the feature or enhancement

It's a good idea to have a GitHub workflow that checks code styles, lint, and formatting. Husky does that already. But it's not effective.

### PR DESCRIPTION
**Pull request by jagadhis**
Hi @mcnaveen would like you to review this pr 

Changes done: 

1. moved from husky and prettier to lefthook and Stylistic eslint
2. added ci/cd pipeline to check for linting when PR is raised

as i have removed some of the dependencies the reason for that is stylistic plugin will by default handle some of the rules if there is any rule we need to add we can further add to the eslintrc file 

---
Resolves #14

### CODE REVIEW

**Comment by mcnaveen** [comment]
Hi @jagadhis Thanks for the PR.
Can you check the action logs for `on-pull-request`. I see a bunch of errors.

Example:
```
1:1  Error: Definition for rule '@stylistic/indent' was not found.  @stylistic/indent
1:1  Error: Definition for rule '@stylistic/quotes' was not found.  @stylistic/quotes
1:1  Error: Definition for rule '@stylistic/object-curly-spacing' was not found.  @stylistic/object-curly-spacing
1:1  Error: Definition for rule '@stylistic/jsx-tag-spacing' was not found.  @stylistic/jsx-tag-spacing
```

**Comment by jagadhis** [comment]
@mcnaveen can you authorize and try it now ?

**Comment by jagadhis** [comment]
@mcnaveen i saw the errors it is typescript i will try to resolve it

**Comment by mcnaveen** [comment]
Okay. I know what is causing these errors now. Maybe #13 will fix these.

**Comment by jagadhis** [comment]
@mcnaveen yeah i should have tackled that first i will fix this first and will try to take on #13 since it is big change

**Comment by mcnaveen** [comment]
Yeah. It's bigger. I planned to work on this today. Once done. I'll have more core features lined up.

**Comment by jagadhis** [comment]
@mcnaveen  this will work i checked in local there was no eslint errors for now i have disabled the rules once we fix issue #13 we can enable it again

**Comment by mcnaveen** [comment]
Awesome, Thanks for your awesome work.
I'm going to merge this now. Do you have a hacktoberfest profile setup already?
https://hacktoberfest.com/

**Comment by jagadhis** [comment]
@mcnaveen nope doing it now

**Comment by jagadhis** [comment]
@mcnaveen i have setup my profile on hacktoberfest thanks for letting me know beofre merging

**Comment by mcnaveen** [comment]
Awesome. Thank you so much for your contribution. 🫡
You'll be added to contributor-only discord channel.

**Comment by mcnaveen** [comment]
@all-contributors please add @jagadhis for code, ideas

**Pull request merged**
